# Generated by Django 5.2.5 on 2025-08-14 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cart_cartitem'),
        ('product', '0002_attribute_brand_attributevalue_product_productimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
